### ISSUE TITLE
long title-attribute breaks thumbnail hover

### ISSUE THREAD

**Issue by pieter-biesemans** [kamilczujowski/least.js-2#8]
When using a long title for an image, it breaks the hover preview.

The images in our gallery are being input by a client, who likes using long titles and doesn't care that it breaks our design (as he shouldn't).

![image](https://cloud.githubusercontent.com/assets/11043199/7882717/c311b3fc-0610-11e5-878a-5060be52d4e8.png)

We've solved it by using a little CSS:

``` css
#least .least-gallery li a:hover:after{
    max-height:30px;
    overflow:hidden;
}
```

But as you can see, it just displays the first 9 or 10 characters and hides the rest. Which is OK.

But maybe javascript could provide a more elegant solution?

![image](https://cloud.githubusercontent.com/assets/11043199/7882778/5b95c122-0611-11e5-97e8-27bd5dfdb867.png)
